### ISSUE TITLE
[sql] Count expressions doesn't work

### ISSUE THREAD

**Issue by SNJiang1992** [tauri-apps/plugins-workspace#183] opened 2022-11-29 07:55 UTC
SELECT COUNT(*) AS 'total' from TABLENAME

return null instead of the right value

**Comment by FabianLars** [comment] 2022-11-29 09:30
Duplicate of tauri-apps/plugins-workspace#10. Thanks for the report!

**Closed as not planned by FabianLars** 2022-11-29 09:30 UTC
