### ISSUE TITLE
[window-state] not working near to screen borders

### ISSUE THREAD

**Issue by romby1** [tauri-apps/plugins-workspace#892] opened 2024-01-13 14:47 UTC
If I place window to the borders of the screen it's not restoring at the same place, but on the previous position before that. In others cases it's restoring correctly 

https://github.com/tauri-apps/plugins-workspace/assets/68077065/9befa3a2-0df8-4373-ba3b-c923d65389de

link to the plugin https://github.com/tauri-apps/tauri-plugin-window-state

**Comment by amrbashir** [comment] 2024-01-16 02:38
can you test if #898 fixes the issue for you?

add the following in your `Cargo.toml` then run `cargo update` inside `src-tauri`:
```toml
[patch.crates-io]
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "fix/window-state/restore-zero-positions" } 
```

**Comment by romby1** [comment] 2024-01-17 10:31
> can you test if #898 fixes the issue for you?
> 
> add the following in your `Cargo.toml` then run `cargo update` inside `src-tauri`:
> 
> ```toml
> [patch.crates-io]
> tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "fix/window-state/restore-zero-positions" } 
> ```

It didn't fixed the issue. Maybe is it possible to make magnetting windows? So they will stick to each other if they have distance lower than 5-10px between them? So users not needed to fit windows by hands and theoretically it will prevent windows go over the sides of screen, if this is the source of the problem

**Comment by romby1** [comment] 2024-01-17 10:48
I also forgot mention that if I maximize window on second monitor (not main), close and open - it restoring maximized but on main monitor

**Comment by amrbashir** [comment] 2024-01-17 18:32
@romby1 thanks for testing, can you give it another try? I believe all issues are now addressed.

> Maybe is it possible to make magnetting windows? So they will stick to each other if they have distance lower than 5-10px between them? So users not needed to fit windows by hands

This is out of the plugin scope.

**Comment by romby1** [comment] 2024-01-17 19:04
> @romby1 thanks for testing, can you give it another try? I believe all issues are now addressed.
> 
> > Maybe is it possible to make magnetting windows? So they will stick to each other if they have distance lower than 5-10px between them? So users not needed to fit windows by hands
> 
> This is out of the plugin scope.

yeah, now I have an error while `cargo update`
![image](https://github.com/tauri-apps/plugins-workspace/assets/68077065/6cb6ae7c-7c85-4fc5-8e62-20798b7d41cc)

**Comment by amrbashir** [comment] 2024-01-18 00:04
Can you share your cargo.toml

**Comment by romby1** [comment] 2024-01-18 14:36
> Can you share your cargo.toml

```
[package]
name = "warden"
version = "0.0.0"
description = "warden"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "updater", "clipboard-all", "process-exit", "notification-all", "window-all", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }

[patch.crates-io]
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "fix/window-state/restore-zero-positions" } 

serde_json = "1.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
```

**Comment by amrbashir** [comment] 2024-01-18 15:23
move `serde_json` dependency up before `[patch.crates-io]` line

**Comment by romby1** [comment] 2024-01-18 15:29
> move `serde_json` dependency up before `[patch.crates-io]` line

fixed the error, but not fixed the main problem

**Comment by amrbashir** [comment] 2024-01-18 16:06
which is? can you share a recording?

**Comment by romby1** [comment] 2024-01-18 17:40
> which is? can you share a recording?

it would be the same as I posted before

**Comment by amrbashir** [comment] 2024-01-18 17:42
can you share your repo then? because I can't reproduce the bug in the recording anymore

**Comment by romby1** [comment] 2024-01-18 17:45
![image](https://github.com/tauri-apps/plugins-workspace/assets/68077065/bfc07e7f-c43c-4322-8d3d-84568274617e)
Btw I getting this warning while `cargo update`, is that the problem?

**Comment by amrbashir** [comment] 2024-01-18 17:49
ah yeah, that maybe the issue, I see in your Cargo.toml you're already using the plugin from git, try removing the `[patch.crates-io]` stuff you added and just change the branch in the dependency above it

**Comment by romby1** [comment] 2024-01-18 17:50
> ah yeah, that maybe the issue, I see in your Cargo.toml you're already using the plugin from git, try removing the `[patch.crates-io]` stuff you added and just change the branch in the dependency above it

Im not sure to what I need change the branch? v2 ?

**Comment by amrbashir** [comment] 2024-01-18 18:13
Here is a diff of what you need to change in your Cargo.toml

```diff
[package]
name = "warden"
version = "0.0.0"
description = "warden"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "updater", "clipboard-all", "process-exit", "notification-all", "window-all", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
+serde_json = "1.0"
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
-tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
+tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "fix/window-state/restore-zero-positions" }

-[patch.crates-io]
-tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "fix/window-state/restore-zero-positions" } 
-
-serde_json = "1.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
```

**Comment by romby1** [comment] 2024-01-18 18:26
Yeah, now it's restoring when window is close the the borders, but something strange happening when I maximized window on second monitor, closed and opened - whole app freeze and stoped working (geting this "white screen"). Tested it several times, not fixing after reopening app. will try to make screen record of 2 monitors (because cant move lagging window to the main monitor )
![image](https://github.com/tauri-apps/plugins-workspace/assets/68077065/51ac4e62-d3c2-46b8-86b5-cd99dded1e4c)

**Comment by romby1** [comment] 2024-01-23 14:16
Actually it happens not only when maximize on another monitor, it will happend just everytime window maximized and closed (video from main monitor)

https://github.com/tauri-apps/plugins-workspace/assets/68077065/0110da06-2820-4a91-8423-137a1c71a67f

**Comment by amrbashir** [comment] 2024-01-23 16:13
Can you ignore the freeze for a second and confirm if other issues are resolved?

As for the freeze, could you share your project or at least a minimal repro?

**Comment by romby1** [comment] 2024-01-24 17:40
Every issues are resolved. Problem with freeze was because of I used manual restoring method, I deleted it and everything fine now. Thank you! Will you changing plugin branch to v2 or something ? Or I can close this topic/post ?

**Comment by amrbashir** [comment] 2024-01-24 17:45
Once the fix is approved, it will be merged and will close automatically.

> Problem with freeze was because of I used manual restoring method

Ah interesting, where were you using this method? maybe we can improve this use-case

**Comment by romby1** [comment] 2024-01-24 17:51
> Once the fix is approved, it will be merged and will close automatically.

What about branch link in my `cargo.toml` file? It look like this now `tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "fix/window-state/restore-zero-positions" }` so I assume it might change...

> Ah interesting, where were you using this method? maybe we can improve this use-case

I used it in begining of code for every window. It looked like this:
```js 
import { restoreStateCurrent, StateFlags } from "tauri-plugin-window-state-api";

restoreStateCurrent(StateFlags.ALL);
```

**Closed as completed** 2024-01-24 23:48 UTC
Labels: type: bug

**Comment by amrbashir** [comment] 2024-01-24 23:52
> > Once the fix is approved, it will be merged and will close automatically.
> 
> What about branch link in my `cargo.toml` file? It look like this now `tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "fix/window-state/restore-zero-positions" }` so I assume it might change...

you, you now need to revert back to `v1` branch

> > Ah interesting, where were you using this method? maybe we can improve this use-case
> 
> I used it in begining of code for every window. It looked like this:
> 
> ```js
> import { restoreStateCurrent, StateFlags } from "tauri-plugin-window-state-api";
> 
> restoreStateCurrent(StateFlags.ALL);
> ```

Ah I see, the plugin restores the positions automatically at window startup as well and since we are using a mutex internally, calling `restoreStateCurrent` will actually deadlock. We can probably make this better but let's just go with recommending not call this command at startup for now and see if more people hit the same issue.
