### ISSUE TITLE
Stronghold plugin running very slowly problem

### ISSUE THREAD

**Issue by ryusei-48** [tauri-apps/plugins-workspace#2052] opened 2024-11-15 07:02 UTC
I am currently developing a very large project at TAURI.
I have adopted the official Stronghold plugin for storing crypto keys and other information, but the Stronghold plugin is very slow in initializing, inserting and reading data, and other operations.
It is excruciatingly slow, especially in development builds, and we have to wait several minutes per action.
I am convinced that the Stronghold plugin is a powerful crypto storage, but the overhead is going to increase dramatically.
Any insights or solutions would be appreciated if you could contact me.
When using the Stronghold plugin, we have implemented it using the following official documentation.
https://v2.tauri.app/plugin/stronghold/

Thanks!

## development environment
```
[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 130.0.2849.80
    ✔ MSVC:
        - Visual Studio Build Tools 2022
        - Visual Studio Community 2022
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 22.10.0
    - pnpm: 9.12.3
    - npm: 10.9.0

[-] Packages
    - tauri 🦀: 2.1.0
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.0
    - tao 🦀: 0.30.6
    - @tauri-apps/api : 2.0.3 (outdated, latest: 2.1.1)
    - @tauri-apps/cli : 2.0.5 (outdated, latest: 2.1.0)

[-] Plugins
    - tauri-plugin-process 🦀: 2.0.1
    - @tauri-apps/plugin-process : 2.0.0
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.1
    - tauri-plugin-http 🦀: 2.0.3
    - @tauri-apps/plugin-http : 2.0.1
    - tauri-plugin-deep-link 🦀: 2.0.1
    - @tauri-apps/plugin-deep-link : not installed!
    - tauri-plugin-fs 🦀: 2.0.3
    - @tauri-apps/plugin-fs : 2.0.1 (outdated, latest: 2.0.2)
    - tauri-plugin-dialog 🦀: 2.0.3
    - @tauri-apps/plugin-dialog : 2.0.1
    - tauri-plugin-single-instance 🦀: 2.0.1
    - @tauri-apps/plugin-single-instance : not installed!
    - tauri-plugin-stronghold 🦀: 2.0.1
    - @tauri-apps/plugin-stronghold : 2.0.0
    - tauri-plugin-store 🦀: 2.1.0
    - @tauri-apps/plugin-store : 2.1.0
    - tauri-plugin-global-shortcut 🦀: 2.0.1
    - @tauri-apps/plugin-global-shortcut : 2.0.0

[-] App
    - build-type: bundle
    - CSP: img-src * blob: blob: data:; connect-src 'self' https://google.github.io/magika/model/ https://www.youtube.com/ https://googleads.g.doubleclick.net/ ipc: http://ipc.localhost; worker-src 'self' blob:; script-src 'self'; style-src 'self' 'unsafe-inline'; frame-src 'self' https://www.youtube.com/embed/; style-src-elem 'self' 'unsafe-inline'; default-src 'self'
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2024-11-15 11:11
thanks for the report, i'll close this as a duplicate of https://github.com/tauri-apps/plugins-workspace/issues/2048

**Closed as not planned by FabianLars** 2024-11-15 11:11 UTC
Labels: type: bug, plugin: stronghold
