### ISSUE TITLE
[Android] plugin-upload download function cant works 

### ISSUE THREAD

**Issue by real-cool** [tauri-apps/plugins-workspace#1731] opened 2024-09-04 09:22 UTC
![image](https://github.com/user-attachments/assets/3cdaace8-8241-4914-a30f-0d254b0e69b1)
i dont know why permission denied, and I have authorized the permission to read and write files， but still not works

**Comment by FabianLars** [comment] 2024-09-04 10:24
The error makes no sense to me tbh but the plugin doesn't work on mobile yet. Closing as duplicate of https://github.com/tauri-apps/plugins-workspace/issues/1156

**Closed as not planned by FabianLars** 2024-09-04 10:24 UTC
Labels: type: question, plugin: http-extra
