### ISSUE TITLE
[feature request] upload plugin, respect original file name from URL during download

### ISSUE THREAD

**Issue by HuakunShen** [tauri-apps/plugins-workspace#2166] opened 2024-12-09 08:09 UTC
The `download` function requires a custom save path.

When downloading a file from an url like `http://localhost:9559/file.txt` we know the filename is `file.txt`.
However, when url doesn't contain filename, we don't know what the original filename is. 
Normally in a browser, adding response header `content-disposition: "attachment; filename=file.txt"` teaches the browser what the downloaded file should be named, but there is not an option in the plugin.

Suggestion: 
When `filePath` passed in is a directory, use the inferred filename.
Currently if a directory is passed in, an error is thrown.

**Comment by FabianLars** [comment] 2024-12-09 10:22
while i do prefer your description (because there actually is one), i'll still close it due to age difference as a duplicate of #271

**Closed as not planned by FabianLars** 2024-12-09 10:22 UTC
Labels: type: feature request, plugin: http-extra
