### ISSUE TITLE
[bug] shell execute doesn't return anything.

### ISSUE THREAD

**Issue by HuakunShen** [tauri-apps/plugins-workspace#1403] opened 2024-06-02 06:43 UTC
I followed this https://beta.tauri.app/plugin/shell/

But the result returned is undefined
<img width="341" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/33727687/f45e5784-01a9-4877-8d53-0923c4dc7e5e">

```js
  let result = await shell.Command.create("exec-sh", ["-c", "echo 'Hello World!'"]).execute();
  console.log("result", result);
  console.log("stdout", result.stdout);
  console.log("stderr", result.stderr);
```

The command is indeed run, but no result is returned.,

Version: `"@tauri-apps/plugin-shell": "2.0.0-beta.6",`

**Comment by amrbashir** [comment] 2024-06-03 18:53
This should be fixed by https://github.com/tauri-apps/plugins-workspace/pull/1328 and duplicate of #1343

**Closed as not planned by amrbashir** 2024-06-03 18:53 UTC
Labels: type: bug, plugin: shell

**Comment by amrbashir** [comment] 2024-06-03 18:55
try running `cargo update -p tauri-plugin-shell` inside `src-tauri`
