### ISSUE TITLE
[upload] Problems with tauri-plugin-upload

### ISSUE THREAD

**Issue by nucleusgenius2** [tauri-apps/plugins-workspace#409] opened 2023-05-29 19:57 UTC
Hello. tauri The only example from the documentation does not work for me.  

import {  download } from 'tauri-plugin-upload-api'

onMounted(async ()=>{
  download(
      'https://my-saite/wp-content/uploads/2017/05/cropped-logo_star5.png',
      '../components/cropped-logo_star5.png',
      (progress, total) => console.log(`Uploaded ${progress} of ${total} bytes`), // a callback that will be called with the upload progress
      { 'Content-Type': 'text/plain' } // optional headers to send with the request
  )
})

I see errors in the console, path not found, file not found, etc.

I don’t understand at all why we specify the path with the file name in the second parameter (judging by the documentation) -"    './path/to/save/my/file.txt'," 

Will be grateful if someone shows a really working code for downloading a file from a remote server through an javascript

**Comment by FabianLars** [comment] 2023-05-30 09:17
So i _think_ the issue is that the plugin currently doesn't create missing directories of the given path. Also, using relative paths won't work after shipping your app so i'd suggest using the [path module](https://tauri.app/v1/api/js/path) which would also make it easier to call createDir beforehand.

> I don’t understand at all why we specify the path with the file name in the second parameter

Because i didn't know how to get the filename from the server back then and now i don't know how to introduce that change without breaking every usage - i'll probably end up making a breaking change nonetheless since cargo doesn't upgrade git dependencies automatically. So only have to think of a good api and a fallback mechanism if the server doesn't send a filename like it's supposed to do.

**Comment by nucleusgenius2** [comment] 2023-05-30 16:48
As per your advice, I used the path. I chose the path for the desktop, checked the variable in the console, the path is valid, but I still get an error:
Uncaught (in promise) The system cannot find the specified path. (os error 3)
download@index.min.js:62

```
import {  download } from 'tauri-plugin-upload-api'
import { desktopDir } from '@tauri-apps/api/path';

onMounted(async ()=>{
  const desktopPath = await desktopDir();

  download(
      'https://my-sait/wp-content/uploads/2017/05/cropped-logo_star5.png',
      desktopPath,
      (progress, total) => console.log(`Uploaded ${progress} of ${total} bytes`), // a callback that will be called with the upload progress
      { 'Content-Type': 'text/plain' } // optional headers to send with the request
  )
})
```

**Comment by FabianLars** [comment] 2023-05-30 17:19
Now you're missing the filename from the destination path.

**Comment by nucleusgenius2** [comment] 2023-05-30 18:46
Yes. I was able to download the picture and the archive. can the plugin extract files from the archive?

**Comment by FabianLars** [comment] 2023-05-30 18:49
No it cannot, it's out of scope for this plugin. afaik there's no plugin that can extract archives yet so this would probably require using rust :/

**Closed as completed by FabianLars** 2023-05-30 18:49 UTC
Labels: type: question

**Comment by nucleusgenius2** [comment] 2023-05-30 18:56
Is it possible to use rust scripts if the project is on js?

**Comment by FabianLars** [comment] 2023-05-30 19:14
Yep, that's one of the main ideas behind tauri: https://tauri.app/v1/guides/features/command
