### ISSUE TITLE
Cargo 1.77 (next version) shows an error

### ISSUE THREAD

**Issue by ciscorn** [tauri-apps/plugins-workspace#1052] opened 2024-03-08 02:56 UTC
I'm using the v1 log plugin and found the next version of Cargo (v1.77) shows an error message:

```
[dependencies]
tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
```

Error message I got:

```
❯ cargo +beta build    
error: invalid character `{` in package name: `tauri-plugin-{{name}}`, characters must be Unicode XID characters (numbers, `-`, `_`, or most letters)
 --> ../../../../../../.cargo/git/checkouts/plugins-workspace-fd0259fcb18f51ad/30295ec/shared/template/Cargo.toml:2:8
  |
2 | name = "tauri-plugin-{{name}}"
  |        ^^^^^^^^^^^^^^^^^^^^^^^
```

Maybe the next version of Cargo will perform more strict error checking against [/shared/template/Cargo.toml](https://github.com/tauri-apps/plugins-workspace/blob/v1/shared/template/Cargo.toml).

**Comment by FabianLars** [comment] 2024-03-08 07:36
Oof that's annoying. It's not even supposed to look at that file :/
Let's see if this will be fixed/changed before stable though. If it does, it's a really quick change we can do on release day.

Thanks for reporting this!

**Comment by lockieluke** [comment] 2024-03-15 17:20
i dont think any of the plugins are usable

**Comment by lockieluke** [comment] 2024-03-18 07:58
what's the ETA on this one

**Comment by FabianLars** [comment] 2024-03-18 08:10
> what's the ETA on this one

> Let's see if this will be fixed/changed before stable though. If it does, it's a really quick change we can do on release day.

Since stable releases this week we'll update it this week too. My todo list for today is quite swamped so maybe tomorrow. Does this cause you any actual problems? For me it just prints the error message but keeps going as if nothing happened.

**Comment by lockieluke** [comment] 2024-03-18 08:12
It just doesn’t build at all when a plugin is added

**Comment by FabianLars** [comment] 2024-03-18 08:25
hmm weird, i don't have any problems. Let me update it now then so you can check if there maybe is another issue unrelated to this.

**Closed as completed** 2024-03-18 08:40 UTC

**Comment by FabianLars** [comment] 2024-03-18 08:41
Don't forget to run `cargo update` so that it pulls the latest commit.

**Comment by p0ryae** [comment] 2024-03-23 23:34
Thanks. I can confirm the error is no longer persistent.
