### ISSUE TITLE
[window-state] App does not resize when opened from a monitor different from the one it closed in

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/plugins-workspace#244] opened 2022-11-04 22:52 UTC
When I close the app in monitor B after resizing, and then open the app from monitor A, the app opens up on monitor B in the same position except it does not get resized. When I open the app from the same monitor as the monitor I closed the app in, the resizing works as expected even after closing the window that was not resized.

App source (please do not use the provided binary) https://github.com/elibroftw/google-keep-desktop-app

Screenshots of Behaviour

Window in right monitor before close 
![image](https://user-images.githubusercontent.com/21298211/200085773-95d85dba-b58b-4aae-820a-415c2946f319.png)
Opening app from left monitor
![image](https://user-images.githubusercontent.com/21298211/200085800-47a3fc8e-bc63-4821-b9a9-2b230c47aa76.png)
Window opens up right monitor but not resized
![image](https://user-images.githubusercontent.com/21298211/200085824-07a6e0f0-ddba-4080-a9ec-5d6d36af97dc.png)
Closed the window and now opening it from the right monitor
![image](https://user-images.githubusercontent.com/21298211/200085860-2b6cb569-c109-422d-8449-959ddae3053e.png)
Window appears properly resized even after being closed with the wrong size
![image](https://user-images.githubusercontent.com/21298211/200085871-2bfcf221-f6b8-45bd-8588-67c6bcb95088.png)

**Comment by amrbashir** [comment] 2022-11-05 12:31
maybe a regression of https://github.com/tauri-apps/tauri-plugin-window-state/commit/2f4cd57b1e7544155484faab769c91c4bf25120e could you try the `size-pos-order` branch and see if it is fixed?

**Comment by elibroftw** [comment] 2022-11-05 20:17
no still not fixed.

**Comment by amrbashir** [comment] 2022-11-05 23:12
Seems like it can't be solved.

The problem is that `set_size` will scale the `size` passed to it based on the `scale_factor` stored on the `Window` instance. In this case, calling `set_size` right after `set_position`, the `scale_factor` will contain the scale factor of the monitor that launched the app because the OS still hasn't emitted the new scale factor so `set_size` will read the wrong value.

The only way this could be solved is if Tauri exposed a way to modify the `WindowBuilder` right before creating the window. cc @lucasfernog. 

I think this could be possible in tauri v2, because it will require creating windows while the event loop is running so tauri can theoretically pass a mutable reference to the event loop which plugins can modify.

**Comment by elibroftw** [comment] 2022-11-06 16:32
Is there no way for a single measurement independent of scale factor? Or at least assimilate this plugin into core since it's such a basic requirement imo.

**Comment by amrbashir** [comment] 2022-11-07 12:05
I don't think this should be added into core, so I will see if I can add the proposed API on tauri side.

**Comment by amrbashir** [comment] 2022-11-07 22:18
@elibroftw Can you test the latest changes in the `dev` branch, I changed the handling to save/restore logical sizes and it might have solved this issue too.

**Comment by elibroftw** [comment] 2022-11-08 00:23
The size does remain the same but now the position isn't always the same but it's not a bother so I'm happy.

**Comment by amrbashir** [comment] 2022-11-08 00:36
Can you show me how much off the position is?

**Comment by elibroftw** [comment] 2022-11-08 02:52
![image](https://user-images.githubusercontent.com/21298211/200463463-cd7b2108-d681-485e-8fbd-292c98a46739.png)
![image](https://user-images.githubusercontent.com/21298211/200463535-805dfef0-09b3-45bd-bace-474d3d1962a8.png)

**Comment by amrbashir** [comment] 2022-11-08 10:42
@elibroftw can you try again? I seem to have missed to save the position as logical units instead of physical.

**Comment by elibroftw** [comment] 2022-11-08 18:07
Same behaviour but now the window also shows up in the default position and size before resizing and moving

**Comment by elibroftw** [comment] 2022-11-08 18:08
I'm not sure if that new bug is caused by the plugin or something on my end though since I even used yesterday's revision and couldn't undo the bug

**Comment by elibroftw** [comment] 2022-11-09 19:34
This information may be useful

> You should also be aware that the coordinate system for window placement is not screen coordinates, but rather workspace coordinates.[ The consequence of getting this wrong is that your window creeps up (or to the left) over time, eventually getting itself stuck underneath the taskbar](http://weblogs.asp.net/oldnewthing/archive/2003/09/12/54896.aspx).

https://stackoverflow.com/questions/29747238/how-to-convert-workspace-coordinates-to-screen-coordinates

**Comment by amrbashir** [comment] 2022-11-11 11:38
> Same behaviour but now the window also shows up in the default position and size before resizing and moving
>
> I'm not sure if that new bug is caused by the plugin or something on my end though since I even used yesterday's revision and couldn't undo the bug

The last commit in the `dev` branch was related to visibility. Try the commit before it or something.

**Comment by amrbashir** [comment] 2022-11-11 11:57
Also make sure you have your window `visible: false` in tauri.conf.json (or in your app code if using the programmatic API).

**Comment by amrbashir** [comment] 2022-11-11 12:06
> The size does remain the same but now the position isn't always the same but it's not a bother so I'm happy.

Since I don't have a multi-monitor setup. I tested the following:
1. open the window on my monitor 1920*1080
2. move the window around, resize it and close it
3. change my monitor resolution in 1400*1050
4. open the app and the window spawned in the correct position with the correct size

I think maybe what you are experiencing is that because one of your monitors has a bigger resolution, it may seem to you that it is not the same position. For example, if your window position is 100px away from the left, on the smaller monitor this is a huge gap but on the bigger monitor it may seem way smaller because there are more pixels.

To confirm this, maybe log the position of the window before you close it and then log it again once you open it on the other monitor.

**Comment by elibroftw** [comment] 2022-11-11 19:06
Please do not invalidate my experience when I posted screenshots of said behaviour. https://github.com/tauri-apps/plugins-workspace/issues/244

It's not in my head, that's the screenshot of the same monitor, I didn't include the second monitor since it was not relevant, but I will include the second monitor here for proof that the window is on the same monitor.

Opening the app from my right monitor:
![image](https://user-images.githubusercontent.com/21298211/201410122-8a268548-6bb4-49c2-b1b8-90e3870883f4.png)
Opening the app from the left monitor:
![image](https://user-images.githubusercontent.com/21298211/201410152-17abd9f7-4ccd-4995-9862-8f22386847b7.png)

Here are the position values when I open the app from left monitor and then the right monitor.
```js
// left
innerPosition: {"type":"Physical","x":574,"y":297}
outerPosition: {"type":"Physical","x":566,"y":266}
// right
innerPosition: {"type":"Physical","x":385,"y":208}
outerPosition: {"type":"Physical","x":377,"y":177}
```
As you can see the position is not as expected. Yes my monitors are different resolutions, however Microsoft TODO does not face this bug.

**Comment by amrbashir** [comment] 2022-11-11 19:15
> Please do not invalidate my experience when I posted screenshots of said behaviour. https://github.com/tauri-apps/plugins-workspace/issues/244

It was not my intention at all, I apologize if it felt that way.

> It's not in my head, that's the screenshot of the same monitor, I didn't include the second monitor since it was not relevant, but I will include the second monitor here for proof that the window is on the same monitor.

That's my bad, thought the position felt wrong for you because I assumed you closed the app on One monitor and tried to open it on the other when the first monitor is disconnected.

> Here are the position values when I open the app from left monitor and then the right monitor.
> ```
> // left
> innerPosition: {"type":"Physical","x":574,"y":297}
> outerPosition: {"type":"Physical","x":566,"y":266}
> // right
> innerPosition: {"type":"Physical","x":385,"y":208}
> outerPosition: {"type":"Physical","x":377,"y":177}
> ```
> As you can see the position is not as expected. Yes my monitors are different resolutions, however Microsoft TODO does not face this bug.

That's expected since it is physical position, can you try converting them to logical? Also if possible record the position right before closing the window the first time and compare it with the value stored in `.window-state` file

**Comment by elibroftw** [comment] 2022-11-11 19:16
Where is the .window-state file in for debug builds?

**Comment by amrbashir** [comment] 2022-11-11 19:18
it is stored in `C:\Users\<username>\AppData\Roaming\<bundle-identifier>`

**Comment by elibroftw** [comment] 2022-11-11 19:18
Also how do I read the `.window-state` file without running code?

**Comment by amrbashir** [comment] 2022-11-11 19:19
ah maybe you need to clone this plugin and add some `println!` to see the values when they are loaded

**Comment by elibroftw** [comment] 2022-11-11 20:34
I decided to just read the source code and figure it out.

https://github.com/tauri-apps/tauri-plugin-window-state/blob/dev/src/lib.rs#L116 

This is the problem, we should use the scale factor from the monitor from the for loop, not the current monitor.

**Comment by elibroftw** [comment] 2022-11-11 20:35
nvm

**Comment by elibroftw** [comment] 2022-11-11 20:35
I'll fork and figure it out myself

**Comment by elibroftw** [comment] 2022-11-11 20:50
The bug is wherever the processing code of set_position is. I just saved the logical position on my right monitor, moved the window to the left monitor and called set position using the logical position I saved and the window had a major offset

**Comment by elibroftw** [comment] 2022-11-11 20:50
setting position via physical position seems to work.

**Comment by elibroftw** [comment] 2022-11-11 20:58
Also, why bother setting a position if there was no position saved? Shouldn't we just let the OS decide how to position the window if there's no position save state?

**Comment by elibroftw** [comment] 2022-11-11 21:12
I fixed the issue in my repo, but I also found that if you maximize the window, close the window, and then open the app from the other monitor, the window does not maximize as expected.

**Comment by elibroftw** [comment] 2022-11-11 21:12
I'll try fixing that too since I think I got the hang of this now

**Comment by amrbashir** [comment] 2022-11-11 22:05
Can you see if saving the physical position fixes the position issue? use `size-physical` branch to test it out.

> but I also found that if you maximize the window, close the window, and then open the app from the other monitor, the window does not maximize as expected.

I think there is already another issue open for this.

**Comment by elibroftw** [comment] 2022-11-11 22:08
Saving the physical does fix the position, it's in my fork.

**Comment by elibroftw** [comment] 2022-11-11 22:09
if it's an issue already I'll open a PR to close this issue at the very least

**Comment by amrbashir** [comment] 2022-11-11 22:10
> Saving the physical does fix the position, it's in my fork.

Yeah, I took a look at it, but you have other changes there that I think is unneeded so if you can confirm that changes in `size-physical` branch is enough, I will go ahead and merge it and close this issue.

**Comment by elibroftw** [comment] 2022-11-11 22:14
Can you take a look at it now? It does the physical size and it removes using (100, 100) as a fallback

**Closed as completed** 2022-11-11 22:51 UTC
