### ISSUE TITLE
[log] [2022-12-28][08:01:34][Error][INFO] Mounting wim file. [Error] is common whether log is info, trace or anything.

### ISSUE THREAD

**Issue by Shivang-idrive** [tauri-apps/plugins-workspace#164] opened 2022-12-28 09:42 UTC
How to get rid of this [Error] and just log file should log [info]...

**Comment by FabianLars** [comment] 2022-12-28 09:53
Duplicate of https://github.com/tauri-apps/plugins-workspace/issues/41

**Closed as not planned by FabianLars** 2022-12-28 09:53 UTC
