### ISSUE TITLE
[bug][v2][shell]In v2, the `docker images` command needs to be triggered twice to get the results correctly, but v1 only needs to be triggered once.

### ISSUE THREAD

**Issue by bling-yshs** [tauri-apps/plugins-workspace#1153] opened 2024-04-07 01:03 UTC
In v2, the `docker images` command needs to be triggered twice to get the results correctly, but v1 only needs to be triggered once.

However, I also tried `echo "abc"`, and I could get the results immediately.

https://github.com/tauri-apps/plugins-workspace/assets/41812674/a6f94b60-2664-49fa-b276-d9b3b3a31694

my code:
```js
const getDockerImageList = async () => {
  console.log("start")
  let command = Command.create("ps", [
    "docker", "images"
  ])
  let result = await command.execute()
  console.log("end")
  console.log(result.stdout)
  images.value = result.stdout
}
```

config:
```json
{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "default",
  "description": "Capability for the main window",
  "windows": [
    "main"
  ],
  "permissions": [
    "path:default",
    "event:default",
    "window:default",
    "app:default",
    "image:default",
    "resources:default",
    "menu:default",
    "tray:default",
    "shell:allow-open",
    "shell:default",
    {
      "identifier": "shell:allow-execute",
      "allow": [
        {
          "name": "ps",
          "cmd": "powershell",
          "args": true,
          "sidecar": false
        },
        {
          "name": "docker",
          "cmd": "docker",
          "args": true,
          "sidecar": false
        }
      ]
    }
  ]
}

```

**Comment by amrbashir** [comment] 2024-04-15 07:01
let's close this as duplicate of #1169 and keep the discussion there

**Closed as not planned by amrbashir** 2024-04-15 07:01 UTC
