### ISSUE TITLE
[notification] `Class app.tauri.notification.NotificationScheduleDeserializer has no default (no arg) constructor` in release mode

### ISSUE THREAD

**Issue by guillemcordoba** [tauri-apps/plugins-workspace#894] opened 2024-01-15 12:21 UTC
I get this error when running an android tauri app in release mode (`npm run tauri android dev -- --release`) with with `tauri-plugin-notification`:
```
01-15 13:16:58.482  4531  4591 I RustStdoutStderr: thread '<unnamed>' panicked at 'Failed to send notification: PluginInvoke(InvokeRejected(ErrorResponse { code: None, message: Some("Class app.tauri.notification.NotificationScheduleDeserializer has no default (no arg) constructor\n at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]"), data: () }))', examples/api/src-tauri/src/lib.rs:115:18
01-15 13:16:58.482  4531  4591 I RustStdoutStderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The error happens when I try to send a notification like this in the setup hook:
```rust
            app.notification().request_permission()?;

            app.notification()
                .builder()
                .title("Hey!")
                .show()
                .expect("Failed to send notification");
```

The code works and the notification is shown in debug mode.

**Comment by FabianLars** [comment] 2024-01-15 13:46
Thanks for the report! Could you also add the output of the `tauri info` command and the plugin version please?

**Comment by guillemcordoba** [comment] 2024-01-15 14:02
```
[holonix:~/projects/tauri/pluginsfork/plugins-workspace/examples/api]$ npm run tauri info

> svelte-app@2.0.0-alpha.9 tauri
> tauri info


[✔] Environment
    - OS: Ubuntu 22.04 X64
    ✔ webkit2gtk-4.1: 2.42.4
    ✔ rsvg2: 2.57.0
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: 1.71-x86_64-unknown-linux-gnu (default)
    - node: 18.19.0
    - yarn: 1.22.21
    - npm: 10.2.3




[-] Packages
    - tauri [RUST]: 2.0.0-alpha.20
    - tauri-build [RUST]: 2.0.0-alpha.13
    - wry [RUST]: 0.35.1
    - tao [RUST]: git+https://github.com/guillemcordoba/tao?branch=dev#53ce9b3381a63dd20e2a1c6401bc006c22288153 (0.24.0)
    - tauri-cli [RUST]: 2.0.0-alpha.18
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.17

[-] App
    - build-type: bundle
    - CSP: connect-src ipc: http://ipc.localhost; default-src 'self' customprotocol: asset:; font-src https://fonts.gstatic.com; img-src 'self' asset: http://asset.localhost blob: data:; style-src 'unsafe-inline' 'self' http://fonts.googleapis.com
    - distDir: ../dist
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite

```

Plugin version: 2.0.0-alpha.7

**Comment by nafdev01** [comment] 2024-07-29 08:46
> I get this error when running an android tauri app in release mode (`npm run tauri android dev -- --release`) with with `tauri-plugin-notification`:
> 
> ```
> 01-15 13:16:58.482  4531  4591 I RustStdoutStderr: thread '<unnamed>' panicked at 'Failed to send notification: PluginInvoke(InvokeRejected(ErrorResponse { code: None, message: Some("Class app.tauri.notification.NotificationScheduleDeserializer has no default (no arg) constructor\n at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]"), data: () }))', examples/api/src-tauri/src/lib.rs:115:18
> 01-15 13:16:58.482  4531  4591 I RustStdoutStderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> The error happens when I try to send a notification like this in the setup hook:
> 
> ```rust
>             app.notification().request_permission()?;
> 
>             app.notification()
>                 .builder()
>                 .title("Hey!")
>                 .show()
>                 .expect("Failed to send notification");
> ```
> 
> The code works and the notification is shown in debug mode.

DId you find a fix for this? I keep running into the same error

**Comment by charlesschaefer** [comment] 2024-08-17 16:11
Hi @guillemcordoba and @nafdev01 were you able to solve this? I'm having the same issue, but now with the version `2.0.0-rc.0`.

I created another issue, but I'll close it as duplicate of this you reported, since the error seems to be the same. 

Here's my `tauri info` output for reference:

```
npm run tauri info

> test-notification@0.0.1 tauri
> tauri info


[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 127.0.2651.105
    ✔ MSVC: Ferramentas de Build do Visual Studio 2022
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 22.3.0
    - npm: 10.8.2

[-] Packages
    - tauri [RUST]: 2.0.0-rc.2
    - tauri-build [RUST]: 2.0.0-rc.2
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 1.5.14
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist/test-notification/browser
    - devUrl: http://192.168.1.4:1420/
    - framework: Angular
    - bundler: Webpack
```

**Comment by nafdev01** [comment] 2024-08-17 17:38
Its an issue with the progaurd rules used when compiling the release APK. I fixed it by setting `isMinifyEnabled` to false in the `build.gradle.kts` file in `gen/android/app`, though it's kind of a hacky fix, it works. You can look through the source code to determine which vital libraries or classes that aren't being compiled and add exclude rules for them.

![image](https://github.com/user-attachments/assets/d4785b43-592e-44a9-9b45-24af2b015c89)

**Comment by charlesschaefer** [comment] 2024-08-18 05:38
> Its an issue with the progaurd rules used when compiling the release APK. I fixed it by setting `isMinifyEnabled` to false in the `build.gradle.kts` file in `gen/android/app`, though it's kind of a hacky fix, it works. You can look through the source code to determine which vital libraries or classes that aren't being compiled and add exclude rules for them.
> Wow, thanks @nafdev01, that worked for me. Do you know what are the implications of turning minify off? Do it impacts performance or functionality or only app size?
> ![image](https://private-user-images.githubusercontent.com/85447426/358860257-d4785b43-592e-44a9-9b45-24af2b015c89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NTg4ODYsIm5iZiI6MTcyMzk1ODU4NiwicGF0aCI6Ii84NTQ0NzQyNi8zNTg4NjAyNTctZDQ3ODViNDMtNTkyZS00NGE5LTliNDUtMjRhZjJiMDE1Yzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA1MjMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZGE1NjRjZjFhNmIyYTE0ZWUxN2MzZDAzMGYxNmI1MzU3YjY1NTFkZjg3YjUzNmQ2YmZiNjY4OGRlNGJjYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1C_jH09tV-KNMWjQuG4QnHxK5yahX0Psf9-tQTI1i3E)

Wow, thanks @nafdev01, that worked for me. Do you know what are the implications of turning minify off? Do it impacts performance or functionality or only app size?

**Comment by nafdev01** [comment] 2024-08-19 08:41
less code obfuscation, which might make reverse engineering it somewhat easier and possible negative impact to performance

**Comment by lucasfernog** [comment] 2024-08-27 17:19
I'll work on fixing the proguard rule. Thanks for the report!

**Closed as completed** 2024-08-27 18:30 UTC
Labels: type: bug, platform: android, plugin: notification
