### ISSUE TITLE
[persisted-scope] Asset protocol not configured correctly for directories after restart

### ISSUE THREAD

**Issue by OrIOg** [tauri-apps/plugins-workspace#25] opened 2022-12-12 22:25 UTC
I may be mistaken as I don't know all the intricate of Tauri or Rust, but it seems to me if I use a `dialog.open` as a directory selector it will [allow the path with allow_directory](https://github.com/tauri-apps/tauri/blob/2901145c497299f033ba7120af5f2e7ead16c75a/core/tauri/src/endpoints/dialog.rs#L199). While the current code when deserializing only use allow_file, rendering is useless ?

I think it might be the cause of the problem I currently have, at least when working with the asset-protocol (feature is enabled)

[Minimal reproduction](https://github.com/OrIOg/vanilla-folder/)
___
Versions:
tauri-plugin-persisted-scope: Used with a github

Tauri info
```
Environment
  › OS: Windows 10.0.19042 X64
  › Webview2: 101.0.1210.32
  › MSVC:
      - Visual Studio Community�2019
      - Visual Studio Build Tools�2019
  › Node.js: 17.3.0
  › npm: 8.3.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.2,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.23.3,

App
  › build-type: bundle
  › CSP: default-src 'self' https://asset.localhost; media-src 'self' https://asset.localhost; img-src 'self' https://asset.localhost; script-src 'self' https://asset.localhost; connect-src https://asset.localhost
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ scripts
  ├─ src
  ├─ src-tauri
  └─ tauri-plugin-persisted-scope
```

**Comment by OrIOg** [comment] 2022-12-13 19:08
Apparently the **fs protocol** does allow to read directories content after restart, but not the **asset protocol**

**Comment by Beanow** [comment] 2022-12-14 19:50
Sorry for the confusion! We're *just* moving to a monorepo to maintain plugins a bit easier.
Thank you for the issue, *with reproduction* and PR. Going to poke around and see if I can get someone to look at it. :smile:

**Comment by OrIOg** [comment] 2022-12-15 20:36
By looking at the issue deeper, it seems like the problem comes from the fact that we're saving the patterns.
Because the `allow_*`or `forbid_*` functions escape the given path with `glob::Pattern::escape`, we're transforming the original pattern into a mess.

We don't see much problem for `allow_file` directly(if Windows isn't used), because no extra characters are added, but in the case of `allow_directory`, `/*` or `/**` is appended depending if it's recursive. 

Example with Windows 10 64bits:

1. `"C:\\Users\\user\\Documents"`
Become
3. `"\\\\[?]\\C:\\Users\\user\\Documents\\**"`,
        `"\\\\[?]\\C:\\Users\\user\\Documents"`,
        `"C:\\Users\\user\\Documents\\**"`,
        `"C:\\Users\\user\\Documents"`,
After restart
4. `"C:\\Users\\user\\Documents"`,
        `"C:\\Users\\user\\Documents\\[*][*]"`,
        `"\\\\[?]\\\\\\[[][?][]]\\C:\\Users\\user\\Documents"`,
        `"\\\\[[][?][]]\\C:\\Users\\user\\Documents"`,
        `"\\\\[?]\\\\\\[[][?][]]\\C:\\Users\\user\\Documents\\[*][*]"`,
        `"\\\\[?]\\C:\\Users\\user\\Documents\\[*][*]"`,
        `"\\\\[?]\\C:\\Users\\user\\Documents"`,
        `"\\\\[[][?][]]\\C:\\Users\\user\\Documents\\[*][*]"`,

Re-escaping wrongly `\*` `\**` for directories and more

**Comment by OrIOg** [comment] 2022-12-18 18:40
Just realised that the .persisted-scope file was 50MB in my project due to this duplication problem

**Comment by salmenf** [comment] 2023-02-12 19:28
I am facing the same issue.

If the user selects `my/path` as a directory (`dialog.open`), I'd expect `my/path/**` to be persisted as the allowed path. Instead, it seems all subpaths *at the moment of selection* are persisted. For example, if I had only `my/path/a.js` and then added `my/path/b.js` later, it would not be allowed since it was not persisted earlier. This also leads to massive .persisted-scope files for large directory trees (e.g. `node_modules`).

I'm implementing a file watcher using the excellent other plugin `tauri-plugin-fs-watch`, and this issue prevents me from moving forward, would love a fix.

**Closed as completed** 2023-06-29 21:23 UTC
Labels: type: bug
