### ISSUE TITLE
[sql] MySql TIMESTAMP returns null

### ISSUE THREAD

**Issue by simmslabs** [tauri-apps/plugins-workspace#204] opened 2022-03-09 07:19 UTC
MySql TIMESTAMP returns null

**Comment by FabianLars** [comment] 2022-05-24 13:47
We only really support a small-ish subset of data types, mainly focused on sqlite, which we consider the main use case, especially since 99% of the times actual sql servers should be behind some kind of api server and not directly accessed from clients...

That said, another PR added `DATETIME` support so maybe you can use this instead (although tbh i'm thinking about removing it again 🤔)

Going to close this for now unless @lucasfernog thinks this is indeed in scope (if it is, we should think about other datatypes too)

**Closed as not planned by FabianLars** 2022-05-24 13:47 UTC

**Comment by HarshilSharaf** [comment] 2023-02-28 18:01
@FabianLars Even i am facing when trying a simple `select * from users ;` query the type `created_on` returns null as it is of type datetime in MySQL db..... Can we expect this feature in near future or not as this are some basic types used in every project?

**Comment by FabianLars** [comment] 2023-02-28 18:13
@HarshilSharaf 

Can you run `cargo update` in your src-tauri dir and try again (make sure you consume the rust side of the plugin from this repo, not the mirror)? There was a commit which was supposed to fix this.

If it still doesn't work please create a new issue with a minimal reproduction example. Thank you.

**Comment by HarshilSharaf** [comment] 2023-02-28 18:16
> @HarshilSharaf
> 
> Can you run `cargo update` in your src-tauri dir and try again (make sure you consume the rust side of the plugin from this repo, not the mirror)? There was a commit which was supposed to fix this.
> 
> If it still doesn't work please create a new issue with a minimal reproduction example. Thank you.

@FabianLars Thank you for a quick reply.
Just FYI i just created a new tauri repo 2 days back.. But i still try running cargo update

**Comment by HarshilSharaf** [comment] 2023-03-01 17:13
> @HarshilSharaf
> 
> Can you run `cargo update` in your src-tauri dir and try again (make sure you consume the rust side of the plugin from this repo, not the mirror)? There was a commit which was supposed to fix this.
> 
> If it still doesn't work please create a new issue with a minimal reproduction example. Thank you.

Hi @FabianLars i've tried running `cargo update` and after that also the datatypes like `TIMESTAMP` , `DATETIME` and `DATE` are returned as null

I've tried this on the tables of my own database as well as some inbuilt databases that came with `MySQL` workbench

Can you please check what is wrong with it?

Also, if possible please add support for `ENUM` dataType in future.


MySQL and MySQL workbench version : `8.0.31`

The code that i am using in angular frontend to query database is as follows:
` const db = await Database.load("mysql://sa:pwd1234@localhost:3306/sakila")`
`await db.select('SELECT last_update FROM store;').then(data=>console.log("Data::",data));`


Also see the below image to see the dataTypes for the DB named `sakila` which comes preinstalled with MySQL workbench

![image](https://user-images.githubusercontent.com/62461329/222215355-99f2c8db-d0ed-42d1-a568-fc140bc5936e.png)

**Comment by FabianLars** [comment] 2023-03-03 12:34
@HarshilSharaf can you try out the `sql/types` branch i pushed yesterday? it should support the respective date and time formats for all drivers, and mysql's enum (as string) too.

one issue is that the dates may be in a different format than you'd expect since i didn't find a way to read them from the database as-is with sqlx (it forces us to decode them into `time` or `chrono` types :/ )

**Comment by HarshilSharaf** [comment] 2023-03-03 17:10
@FabianLars I've checked out that branch and it worked successfully.
Also, the date and time are being fetched correctly and in the correct format.
If possible please merge this to the dev branch. Thanks

**Comment by FabianLars** [comment] 2023-03-03 17:14
Oh the format being correct is nice!

And yes I will merge it soon. Was just waiting for a review of some kind. Your test counts too in that regard. Thanks for testing!
