### ISSUE TITLE
[bug][http][v2] Using FormData in HTTP without setting Content Type

### ISSUE THREAD

**Issue by DWHengr** [tauri-apps/plugins-workspace#1485] opened 2024-06-19 13:22 UTC
my code is as follows:
```js
    const formData = new FormData();
    formData.append("param", "123456");
    let token = await invoke("get_user_info", {}).then(res => {
        return res.token
    })
    await fetch(SERVICE_URL + url, {
        method: "POST",
        body: formData,
        headers: {
            "x-token": token ? token : ""
        }
    })
```
The content obtained in springboot is as follows, and there is no Content Type content in the headers.
![image](https://github.com/tauri-apps/plugins-workspace/assets/55067857/7b7f67d9-38cb-44b0-be8b-c7cbe7e9fc78)

If I fix 'Content Type' in the headers: 'multipart/form data;'. Springboot will report an error because the boundary needs to be calculated when sending again. When calling the springboot interface in postman, it will automatically add 'Content Type': ` multipart/form data` And boundary.
![image](https://github.com/tauri-apps/plugins-workspace/assets/55067857/3571aa2d-7363-4371-b0b4-5c8873a110fd)

**Comment by amrbashir** [comment] 2024-06-27 05:28
I can't reproduce and this should be fixed by https://github.com/tauri-apps/plugins-workspace/pull/1354 , please make sure you're using the latest version of the plugin

**Closed as not planned by amrbashir** 2024-06-27 05:28 UTC
Labels: type: bug, plugin: http

**Comment by holai** [comment] 2025-11-15 18:51
I also encountered
