### ISSUE TITLE
[localhost] when I integrated the lib.rs code, reported an error

### ISSUE THREAD

**Issue by Jzow** [tauri-apps/plugins-workspace#157] opened 2022-06-19 18:48 UTC
Because I update crates synchronously in my country The crates.io source and pulling GitHub are very slow, so I have to integrate first. When I refer to the example, there is an error in the runtime.

```rust
#![cfg_attr(
  all(not(debug_assertions), target_os = "windows"),
  windows_subsystem = "windows"
)]

mod cors;

use tauri::{window::WindowBuilder, WindowUrl};

fn main() {
  let port = portpicker::pick_unused_port().expect("failed to find unused port");

  tauri::Builder::default()
    .plugin(cors::Builder::new(port).build())
    .setup(move |app| {
      WindowBuilder::new(
        app,
        "main".to_string(),
        WindowUrl::External(format!("http://localhost:{}", port).parse().unwrap()),
      )
      .title("Localhost Example")
      .build()?;
      Ok(())
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}

```

error log:

```rust
warning: `app` (bin "app") generated 3 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 7.29s
     Running `target/debug/app`
thread 'main' panicked at 'error while running tauri application: Setup(SetupError(WindowLabelAlreadyExists("main")))', covid-ipfs-client/app/src/main.rs:26:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::expect
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1022:23
   4: app::main
             at ./covid-ipfs-client/app/src/main.rs:13:3
   5: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
终端进程“cargo 'run', '--package', 'app', '--bin', 'app'”已终止，退出代码: 101。
```

**Comment by Jzow** [comment] 2022-06-19 18:50
I'm new to tauri，Tauri is a great project

**Comment by lucasfernog** [comment] 2022-06-19 18:55
Duplicate of tauri-apps/plugins-workspace#160, check out the solution there.

**Closed as completed by lucasfernog** 2022-06-19 18:55 UTC

**Comment by Jzow** [comment] 2022-06-19 19:19
> #11的副本，查看那里的解决方案。

thanks
