### ISSUE TITLE
[notification] notification.is_permission_granted not allowed on window main

### ISSUE THREAD

**Issue by parola05** [tauri-apps/plugins-workspace#1318] opened 2024-05-14 14:11 UTC
I am trying to use the notification plugin and I am getting this error: **_`Uncaught (in promise) notification.is_permission_granted not allowed on window main, webview main, allowed windows: , allowed webviews: , referenced by`_** . 

Here are my _**main.json**_ cabalitities file:
```rs
{
  "$schema": "../gen/schemas/mobile-schema.json",
  "identifier": "mobile-capability",
  "windows": ["main"],
  "platforms": ["iOS", "android"],
  "permissions": [
    "nfc:allow-scan",
    "notification:allow-is-permission-granted",
    "notification:allow-notify"
  ]
}
```

And i am trying to use the plugin in my _Vue app_:

```js
import {
    isPermissionGranted,
    requestPermission,
    sendNotification,
} from '@tauri-apps/plugin-notification';

export default {
    async mounted() {
        let permissionGranted = await isPermissionGranted();
        if (!permissionGranted) {
            const permission = await requestPermission();
            permissionGranted = permission === 'granted';
        }
        if (permissionGranted) {
            sendNotification('Tauri is awesome!');
            sendNotification({ title: 'TAURI', body: 'Tauri is awesome!' });
        }
    },
```

Finally, I also register the plugin:

```rust
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_nfc::init())
        .plugin(tauri_plugin_notification::init())
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

**Comment by amrbashir** [comment] 2024-05-14 14:32
duplicate of https://github.com/tauri-apps/tauri/issues/9502

**Closed as not planned by amrbashir** 2024-05-14 14:32 UTC

**Comment by Jovian-Dsouza** [comment] 2024-12-21 18:26
facing same issue, any fix on this yet
