### ISSUE TITLE
[http][v2]  not supports https

### ISSUE THREAD

**Issue by nawbc** [tauri-apps/plugins-workspace#1067] opened 2024-03-12 07:37 UTC
```
error sending request for url (https://upload.twitter.com/1.1/media/upload.json): error trying to connect: invalid URL, scheme is not http
handleError@
```

capabilities
```json
[    
   {
      "identifier": "http:allow-fetch",
      "allow": [
        {
          "url": "https://*"
        }
      ]
    },
    {
      "identifier": "http:default",
      "allow": [
        {
          "url": "https://*"
        }
      ]
    }
  ]
```

<details>
<summary>Sys Info</summary>
<code>
  System:
    OS: Linux 6.7 EndeavourOS
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 2.43 GB / 15.40 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.4.0 - ~/.nvs/default/bin/node
    Yarn: 3.6.3 - ~/.nvs/default/bin/yarn
    npm: 9.7.2 - ~/.nvs/default/bin/npm
    pnpm: 8.12.0 - ~/.nvs/default/bin/pnpm
    bun: 1.0.25 - ~/.local/share/mise/installs/bun/latest/bin/bun
    Watchman: 20231109.143709.0 - /usr/bin/watchman
  Managers:
    Cargo: 1.76.0 - ~/.cargo/bin/cargo
    pip3: 24.0 - /usr/bin/pip3
    RubyGems: 3.3.25 - /usr/bin/gem
  Utilities:
    CMake: 3.28.3 - /usr/bin/cmake
    Make: 4.4.1 - /usr/bin/make
    GCC: 13.2.1 - /usr/bin/gcc
    Git: 2.44.0 - /usr/bin/git
    Clang: 16.0.6 - /usr/bin/clang
    Ninja: 1.11.1 - /usr/bin/ninja
    FFmpeg: 6.1.1 - /usr/bin/ffmpeg
    Curl: 8.6.0 - /usr/bin/curl
  Virtualization:
    Docker: 24.0.6 - /usr/bin/docker
  SDKs:
    Android SDK:
      API Levels: 31, 33, 34
      Build Tools: 30.0.3, 33.0.1, 34.0.0
      System Images: android-33 | Google Play Intel x86_64 Atom
  IDEs:
    Android Studio: AI-223.8836.35.2231.11005911
    Nano: 7.2 - /usr/bin/nano
    VSCode: 1.86.0 - /usr/bin/code
  Languages:
    Bash: 5.2.26 - /usr/bin/bash
    Go: 1.21.4 - /usr/bin/go
    Java: 17.0.9 - /usr/bin/javac
    Perl: 5.38.2 - /usr/bin/perl
    Protoc: 25.2 - /usr/bin/protoc
    Python: 3.11.7 - /usr/bin/python
    Python3: 3.11.7 - /usr/bin/python3
    Ruby: 3.0.6 - /usr/bin/ruby
    Rust: 1.76.0 - /home/nawbc/.cargo/bin/rustc
  Databases:
    SQLite: 3.45.1 - /usr/bin/sqlite3
</code>

</details>

**Comment by amrbashir** [comment] 2024-03-12 16:45
this works just fine on my Windows machine, could you provide a minimal repro?

**Comment by nawbc** [comment] 2024-03-13 02:26
> this works just fine on my Windows machine, could you provide a minimal repro?

I added the `default-lts` feature and it works fine. i will give u the repo later.

**Comment by sebasptsch** [comment] 2024-04-07 00:32
Further discussion here: https://discord.com/channels/616186924390023171/1090533683024363592

**Comment by gato25** [comment] 2024-04-07 01:38
> > this works just fine on my Windows machine, could you provide a minimal repro?
> 
> I added the `default-lts` feature and it works fine. i will give u the repo later.

Hello, can you show how you managed this work ?

**Comment by FabianLars** [comment] 2024-04-07 10:03
@gato25 In your src-tauri/Cargo.toml file you should have a dependency looking something like this:
```toml
tauri-plugin-http = "2.0.0-beta"
```
Change it to this:
```toml
tauri-plugin-http = { version = "2.0.0-beta", features = ["rustls-tls"] }
```
If you have problems with rustls, swap the feature with `default-tls` as mentioned above (rustls-tls is easier to build and distribute so i'd recommend starting out with it).

**Comment by amrbashir** [comment] 2024-04-08 23:46
closing as this sounds like expected behavior that can be tweaked through feature flags

**Closed as completed by amrbashir** 2024-04-08 23:46 UTC
Labels: type: bug

**Comment by FabianLars** [comment] 2024-04-09 11:51
maybe we should enable rustls-tls by default (and removing the default-tls flag because native-tls is an alias for it)? No https support by default honestly makes no sense to me to a degree where i think docs are not enough.

**Comment by slimandslam** [comment] 2024-04-09 15:17
> maybe we should enable rustls-tls by default (and removing the default-tls flag because native-tls is an alias for it)? No https support by default honestly makes no sense to me to a degree where i think docs are not enough.

Yes. I think a sensible default would be allowing HTTP over localhost only, and allowing HTTPS (but scope definition is required to call anywhere, of course)
