### ISSUE TITLE
[shell] How to open a file using system default app in android?

### ISSUE THREAD

**Issue by FlysoftBeta** [tauri-apps/plugins-workspace#652] opened 2023-10-11 15:03 UTC
I would like a button that can save a xlsx file to downloads and then open it using the default app in android.
edit: maybe relate to https://github.com/tauri-apps/plugins-workspace/issues/595?

**Comment by amrbashir** [comment] 2023-10-11 17:11
Ineed it is duplicate of #595

**Closed as not planned** 2023-10-11 17:11 UTC
