### ISSUE TITLE
[fs] Missing "append" in FSOptions.

### ISSUE THREAD

**Issue by mshaa1** [tauri-apps/plugins-workspace#810] opened 2023-12-10 10:24 UTC
Hello everyone! 
I recently upgraded Tauri from the stable to the latest alpha version to see how my voice recorder works on Android, 
but I noticed that the FSOption "append", that I was using with writeBinaryFile to continuously write raw data coming from the microphone into a file, is missing.

**Comment by FabianLars** [comment] 2023-12-10 10:51
Duplicate of #2 and already added in https://github.com/tauri-apps/plugins-workspace/pull/751 which will probably make it into the next alpha release so i doubt we'll add it to the current api. Thanks for the request nonetheless :)

**Closed as not planned by FabianLars** 2023-12-10 10:51 UTC
Labels: plugin: fs
